### ISSUE TITLE
Add a compact description of definition and motivation of this list.

### ISSUE THREAD

**Issue by tfoerst3r** [hifis-net/awesome-rse-fair#1]
- I do not know what FAIR means, maybe add some definition

**Comment by tobiashuste** [comment]
I think this is a good chance to learn what FAIR refers to and to document it in the repo. Would be nice if you could overtake this, @tfoerst3r.

**Comment by Drake81** [comment]
The first link under the heading provides the definition: https://rd-alliance.org/group/fair-research-software-fair4rs-wg/outcomes/fair-principles-research-software-fair4rs-0
